@tenantid = 70b87ecb-180d-460e-8397-552f53f5509a
@baseuri = 712e099b-760d-43bd-b583-f42b79506fbc.westeurope.azurecontainer.io/
@useragent = VsCodeRest-{{$processEnv USERNAME}}-{{$processEnv COMPUTERNAME}}


###
# @name Get-Health
GET http://{{baseuri}}/
Api-Version: 1
Content-Type: application/json
User-Agent: {{useragent}}
